### ISSUE TITLE
can't make dense vector tiles

### ISSUE THREAD

**Issue by JulieGoldberg** [tilezen/TileStache#118] opened 2016-02-29 16:16 UTC
I'm trying to generate vector tiles that include all the polls in Vancouver, BC.  (Polls are small electoral districts -- precincts in US terms -- and are usually a few blocks in size.)  I can generate them in rural areas in Canada, but other urban areas fail as well.  My guess is that there is too much data being included in a single tile, but I'm not sure.  I've tried increasing shape simplification or turning it off entirely to no avail.  It seems to fail after the database query to find the shapes is complete, since it hangs but there are no running queries on my database.  If you want a dump of the problematic data and a tile address that fails, I'm happy to provide it.  

Thanks!

**Comment by nvkelso** [comment] 2016-02-29 16:58
You might try turning tiny "polls" into point geometries (but keeping the big ones as polygons)?

**Comment by JulieGoldberg** [comment] 2016-02-29 17:12
There are polls that are just one apartment building, but most are a few blocks.  The ones that are a single apartment building have a cut-out from another poll.  If that is indeed the problem, we could potentially drop polls that are below a certain square mileage and merge them into adjacent or surrounding polls; we'd then need to use different shapes at different zoom levels.  Can tile generation even handle that?  I would expect simplification supposed to handle the shapes of polls.  Why is it crashing on complex polygon data?

**Comment by rmarianski** [comment] 2016-02-29 17:45
Do you eventually get an error with a stack trace? Or does data eventually come through? If it's just hanging, you might want to profile it a little bit to pinpoint where the slow part is.

**Comment by JulieGoldberg** [comment] 2016-02-29 20:33
Data never comes through, and the tile is never returned.  If it did, it would be cached on S3, so there would be no problem requesting the tile another time.  

I tried upping our logs from info to debug, and I don't see anything useful.  

Where/how do you recommend I put in profiling?

**Comment by rmarianski** [comment] 2016-02-29 20:42
I'd try something simple first. If you can reproduce it locally, you can just step through the provider that generates the data to see what statement it hangs on. Or you could add in your own logging statements in the provider to see how far it gets.

**Comment by JulieGoldberg** [comment] 2016-03-01 18:31
I don't know where it actually fails in the code, but I know what sort of shapes cause it now.  It's caused by tiny shapes.

In Canada, their polling districts may be a few city blocks in urban areas.  But when they have a big apartment building, it's a polling district all to itself.  Its shape is cut out from the surrounding one, but it's land mass is tiny.  The biggest such polling district is 0.05 square miles, and the smallest is  0.00005 sq miles.  I don't know where it that range things start to break, but removing those tiny districts solves the problem and allows the vector tiles to be generated.  I don't need to do anything to change the districts these polls are cut out from.

I suspect there's a division by 0 problem.

**Comment by nvkelso** [comment] 2016-03-01 19:09
Which tile format are you requesting? Sometimes problems that manifest in MVT or GeoJSON work in TopoJSON for instance.

**Comment by JulieGoldberg** [comment] 2016-03-01 19:16
This is only a problem for mvt tiles.  

I also generate image and utf grid tiles from these shapes, and those have no problems with the tiny shapes.

**Comment by nvkelso** [comment] 2016-03-01 19:21
Can you try for another vector format like TopoJSON or GeoJSON?

**Comment by JulieGoldberg** [comment] 2016-03-01 19:31
Both of those seem to work fine.  It's an MVT problem.  And I need MVT tiles.

**Comment by nvkelso** [comment] 2016-03-01 20:50
Are you pre-simplifying geometry in PostGIS as part of the queries, depending on the zoom? Is there a link to a config file &/or data files?

**Comment by JulieGoldberg** [comment] 2016-03-01 21:40
I can email problematic data somewhere or post it somewhere public.  It's currently just in my db.  

We aren't doing any pre-simplification.  We do ensure validity and change the projection when we load districts originally, but that's it.

**Comment by rmarianski** [comment] 2016-03-01 22:23
Is it during the mvt encoding that it actually fails? Can you create a small test case from your data that reproduces the problem?

**Comment by JulieGoldberg** [comment] 2016-03-02 01:05
I'm 95% sure this data set will fail.  It's hard for me to run it with this limited set to confirm.  It's very likely probably due to the smallest polls.  
[problematic_for_vector_tiles.zip](https://github.com/mapzen/TileStache/files/153907/problematic_for_vector_tiles.zip)

**Comment by JulieGoldberg** [comment] 2016-03-09 16:19
Were you able to see it fail with this dataset?  Or where are we on this?

**Comment by nvkelso** [comment] 2016-03-09 18:27
Can you provide a GeoJSON tile (tile coordinate and raw JSON output as an attached file) that is working so we can figure out why MVT is failing?

It could be the problem is in this old TileStache configuration, which we don't currently use in production and don't currently support. We now recommend using our [tileserver](https://github.com/mapzen/tileserver) to serve the tiles. Does using that config fix this problem?

**Comment by peckjon** [comment] 2016-03-09 23:54
Hi - taking over for Julie while she is on vacation.

We've pinned this down to a load problem instead of a hard failure.  Generating the MVTs for this dataset is MUCH more processor-intensive than generating GeoJSON.  Run one-at-a-time, we can get the MVTs to generate but it takes 30-60 seconds for each one (on an otherwise unused AWS t2.large).  So rendering an entire map pegs the CPU and locks up the whole server.

The same GeoJSON tiles generate just fine... hardly any CPU bump at all.  Unfortunately, switching to JSON isn't an option for us (MapboxGL does not support Tiled GeoJSON).

Any idea why MVTs take so much more CPU?

**Comment by nvkelso** [comment] 2016-03-10 00:03
Thanks for the additional information. 

Can you provide a GeoJSON tile (tile coordinate and raw JSON output as an attached file) that is working so we can figure out why MVT is failing?

**Comment by peckjon** [comment] 2016-03-10 00:14
[private_server]/10/163/350.json

[350.zip](https://github.com/mapzen/TileStache/files/166331/350.zip)

**Comment by nvkelso** [comment] 2016-03-10 00:18
Cool, thanks. We'll have a look at it tomorrow morning (EST / London time). Do you have a publish deadline you're working against?

**Comment by peckjon** [comment] 2016-03-10 00:21
Thanks for asking.  While we'd love to get it fixed within a week, our hard deadline is 2-3 weeks.

**Comment by zerebubuth** [comment] 2016-03-10 15:02
I wrote a [small program](https://gist.github.com/zerebubuth/4cabee85c519b3889527) to transcode GeoJSON to MVT, and got an MVT tile which was 53,291 bytes long rather than 57,749 as expected. And took only 0.9s rather than the expected 30-60s. I wonder if we might be using different versions of that library?

@peckjon, it would be really helpful if you could try out the small program above - it should take the GeoJSON as input like this: `time python test.py 350.json` and let us know if that's also slow, please? It would also be helpful to know what version of the `mapnik_vector_tile` module is installed. Thanks!

**Comment by rmarianski** [comment] 2016-03-10 15:50
There have been some performance optimizations made relatively recently, in particular of the encoding of properties. If you're not already using the latest mapbox-vector-tile version, I suggest trying the latest to release to see if it speeds it up.

**Comment by peckjon** [comment] 2016-03-10 20:16
Thanks, @rmarianski -- with the latest version it pegs the CPU but does not deadlock, which is sufficient for us... we can simply restart the requests for the uncached tiles after the CPU settles down.

**Comment by nvkelso** [comment] 2016-03-11 18:49
Great to hear, would love to see your map when it's published.

**Closed as completed** 2016-03-11 18:49 UTC
